name: 'Fetch version tag on HEAD'
description: 'Fetch version tag on HEAD'

outputs:
  VERSION:
    description: "Version on HEAD"
    value: ${{ steps.version.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Fetch tags
      shell: bash
      run: |
        git fetch --tags
    - name: Find version tag
      id: version
      shell: bash
      run: |
        export VERSION=$(git tag --points-at HEAD --sort=-version:refname "dev-*" | sed -n 1p)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV