# we are not actually building/testing with this code, we are just doing a simulation to evaluate the concurrency option
name: performance test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name of the test new environment'
        required: true
        
concurrency: 
  group: tests-on-pr-${{ github.head_ref }}
  #group: build-and-test
  cancel-in-progress: true 

jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    name: Build and Test On Pull Request
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Output HeadRef
        run: echo "${{ github.inputs.name }}"
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
