name: deploy dev

on:
  workflow_call:

defaults:
  run:
    shell: bash

    
    
jobs:
  # This workflow contains a single job called "create"
  deploy-dev:
    name: Deploy dev
    outputs:
      TAG_TO_CHECK_OUT: ${{ steps.version.outputs.VERSION }}
      BETA_VERSION: ${{ steps.echo-version.outputs.BETA_VERSION }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Find latest dev version
        id: version
        uses: ./.github/actions/get-version-from-tag/
        

      - name: Create beta version
        id: beta-version
        shell: bash
        run: echo "${{ steps.version.outputs.VERSION }}"

      - name: Echo to Output
        id: echo-version
        run: |
         echo "BETA_VERSION=$(echo "${{ steps.version.outputs.VERSION }}" | sed 's/dev/BETA/g')" >> $GITHUB_OUTPUT      

      - name: Echo beta
        run: |
          echo "${{ steps.echo-version.outputs.BETA_VERSION}}"
  build:
    name: Build artifact
    needs: 
      - deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ needs.deploy-dev.outputs.TAG_TO_CHECK_OUT }}

