# we are not actually building/testing with this code, we are just doing a simulation to evaluate the concurrency option
name: performance test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name of the test new environment"
        required: true

jobs:
  call-create-workspace:
    uses: ./.github/workflows/create-ws.yml
    with:
      name: ${{inputs.name}}

  run-performance-test:
    runs-on: ubuntu-latest
    needs: call-create-workspace
    steps:
      - name: Output input name
        run: echo "${{inputs.name}}"

      - name: Output actor name
        run: echo "${{github.triggering_actor}}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: run performance test
        run: |
          echo "running test"
          sleep 45s
          echo "Finish test"

  call-destroy-workspace:
    uses: ./.github/workflows/destroy-ws.yml
    needs: run-performance-test
    if: always()
    with:
      name: ${{inputs.name}}
