# we are not actually building/testing with this code, we are just doing a simulation to evaluate the concurrency option
name: performance test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name of the test new environment"
        required: true

jobs:
  call-create-workspace:
    uses: ./.github/workflows/create-ws.yml
    with:
      name: ${{github.event.inputs.name}}

  run-performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Output input name
        run: echo "${{github.event.inputs.name}}"

      - name: run performance test
        run: |
          echo "running test"
          sleep 1m
          echo "Finish test"

  call-destroy-workspace:
    uses: ./.github/workflows/destroy-ws.yml
    needs: run-performance-test
    if: always()
    with:
      name: ${{github.event.inputs.name}}
