name: Push To Main

on:
  push:
    branches:
    - main

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    
    runs-on: ubuntu-latest

    steps:
      - name: Build The Code
        run: |
          echo "Starting Code Build"
          sleep 2m
          echo "Finish Code Build"
      
  deploy:
    name: Deploy
    needs:
    - build
    concurrency: 
      group: my-deploy
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy The Code
        run: |
          echo "Starting Code Deploy"
          sleep 2m
          echo "Finish Code Deploy"
