name: Trigger Repo Dispatch

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  trigger-repo-dispatch:
   
    runs-on: ubuntu-latest

    steps:
    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          repository: mickeygoussetorg/experimentation
          event-type: deploy-code
          client-payload: '{"foo" : "bar"}'
